OnlinePharmacy/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinePharmacy.DataAccess.Repository.IRepository;
using OnlinePharmacy.Models;

namespace OnlinePharmacy.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _unitOfWork.Category.GetAll();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryfromDb = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == id);
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryfromDb = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == id);
            if (categoryfromDb == null)
            {
                return NotFound();
            }
            return View(categoryfromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction("Index");

        }

    }

}

OnlinePharmacy/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinePharmacy.DataAccess.Repository.IRepository;
using OnlinePharmacy.Models;

namespace OnlinePharmacy.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitofwork;

        public CompanyController(IUnitOfWork unitofwork)
        {
            _unitofwork = unitofwork;


        }
        public IActionResult Index()
        {

            return View();
        }

        //Get Create and Update
        public IActionResult Upsert(int? id)
        {

            Company company = new();
            if (id == null || id == 0)
            {
                //Create Product
                return View(company);
            }
            else
            {
                Company company1 = _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);

                return View(company1);
                //Update Product

            }


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitofwork.Company.Add(company);
                    TempData["success"] = "Company Created Successfully";
                }
                else
                {
                    _unitofwork.Company.Update(company);
                    TempData["success"] = "Company Updated Successfully";
                }

                _unitofwork.Save();

                return RedirectToAction("Index");
            }
            return View(company);
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var CompanyList = _unitofwork.Company.GetAll();
            return Json(new { data = CompanyList });
        }
        [HttpDelete]

        public IActionResult Delete(int? id)
        {
            var obj = _unitofwork.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            _unitofwork.Company.Remove(obj);
            _unitofwork.Save();
            return Json(new { success = true, message = "Delete Successfully" });
            return RedirectToAction("Index");


        }
        #endregion


    }

}

OnlinePharmacy/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinePharmacy.DataAccess.Repository.IRepository;
using OnlinePharmacy.Models;

namespace OnlinePharmacy.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> products = _unitOfWork.Product.GetAll(includeProperties: "Company,Category");
            return View(products);
        }
    }
}

OnlinePharmacy/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using OnlinePharmacy.DataAccess.Repository.IRepository;
using OnlinePharmacy.Models;

namespace OnlinePharmacy.Controllers
{
    public class RoleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public RoleController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Role> roles = _unitOfWork.Role.GetAll();
            return View(roles);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Role role)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Role.Add(role);
                _unitOfWork.Save();
                TempData["success"] = "Role Created Successfully";
                return RedirectToAction("Index");
            }
            return View(role);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var rolefromDb = _unitOfWork.Role.GetFirstOrDefault(c => c.Id == id);
            if (rolefromDb == null)
            {
                return NotFound();
            }
            return View(rolefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Role.Update(role);
                _unitOfWork.Save();
                TempData["success"] = "Role Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(role);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var rolefromDb = _unitOfWork.Role.GetFirstOrDefault(c => c.Id == id);
            if (rolefromDb == null)
            {
                return NotFound();
            }
            return View(rolefromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Role.GetFirstOrDefault(c => c.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Role.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Role Deleted Successfully";
            return RedirectToAction("Index");

        }

    }

}

OnlinePharmacy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlinePharmacy</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/OnlinePharmacy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="icon" href="~/favicon.png"/>
</head>
<body>
    <header>
               <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
     <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>OnlinePharmacy</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Category" asp-action="Index">Category</a>
        </li>
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Company" asp-action="Index">Company</a>
        </li>
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Index">Product</a>
        </li>
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Role" asp-action="Index">Role</a>
        </li> 
        <li class="nav-item">
         <a class="nav-link " asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa fa-shopping-cart" aria-hidden="true"></i> (0)</a>
        </li>
       


        @* <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@


      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item d-flex me-2">
         <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item d-flex me-2 ">
         <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
        </li>
      </ul>
 
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlinePharmacy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlinePharmacy/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["success"]');    
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.error('@TempData["error"]');    
    </script>
}